baseURL = "https://NeekzenTutorials.github.io/Portfolio.git"
title = "Mon Blog"
languageCode = "fr-fr"
theme = "hugo-coder"
author = "Nathan Fourny"

# Params supplémentaires pour personnaliser
paginate = 5
disqusShortname = "votre-disqus-shortname"  # Si vous utilisez Disqus pour les commentaires

[params]
  description = "Ceci est mon site personnel."
  # D'autres configurations spécifiques au thème
